import { streamChatWithMetadata, type AiExecutionMetadata } from "@/lib/ai-stream";
import { supabase } from "@/integrations/supabase/client";
import { contentAssistantCalendarStatus, creativeHandoffResult, sanitiseMarketingOutput } from "@/lib/operational-truth";
import { COSSA_ORGANISATION_ID } from "@/lib/workforce-data";
import { getMarketingDestinationLinks, resolveMarketingDestination } from "@/lib/marketing-links";
import { socialBusinessKnowledge, socialObjectiveGuidance, type SocialBusinessKey, type SocialObjective } from "@/lib/social-business-intelligence";
const db = supabase as unknown as { from: (table: string) => any };
export function sanitiseMarketingText(value: unknown): string { return sanitiseMarketingOutput(value); }
export function rewriteContentCommand(input:{instruction:string;mode:"shorter"|"stronger"|"platform";platform?:string;}):string { const p=input.platform?.trim()||"the selected platform"; if(input.mode==="shorter")return `Rewrite this shorter for ${p}:\n${input.instruction}`; if(input.mode==="stronger")return `Rewrite this with a clearer, stronger customer benefit for ${p}:\n${input.instruction}`; return `Adapt this for ${p}; keep it customer-ready and natural:\n${input.instruction}`; }
export async function generateContentDraft(input:{instruction:string;platform:string;onToken?:(text:string)=>void;}):Promise<{content:string;metadata:AiExecutionMetadata}>{const instruction=input.instruction.trim();if(!instruction)throw new Error("Describe the content you want to create.");const result=await streamChatWithMetadata([{role:"user",content:instruction}],input.onToken??(()=>undefined),{provider:"auto",system:["You are the Cossa Content Assistant.",`Write only polished customer-ready copy for ${input.platform||"the requested channel"}.`,"Use concise, natural South African business English.","Do not use markdown, headings, bullets, labels, code fences, internal notes, model metadata or reasoning.","Do not claim a post was published, an image was generated, or an external action was completed."].join(" ")});const content=sanitiseMarketingText(result.content);if(!content)throw new Error("The content provider returned no usable customer-facing copy.");return{content,metadata:result.metadata};}
export type SocialContentPack={title:string;hook:string;caption:string;content:string;hashtags:string;cta:string;best_time:string;visual_idea:string;destination_key:string;link:string;business_key:string;objective:string;};
export async function generateSocialContentPack(input:{instruction:string;platform:string;business?:SocialBusinessKey;objective?:SocialObjective;}):Promise<{pack:SocialContentPack;metadata:AiExecutionMetadata}>{
 const instruction=input.instruction.trim();if(!instruction)throw new Error("Tell the Social Media Assistant what you want, for example: NexDocs pain-point post.");
 const business=input.business??"auto";const objective=input.objective??"auto";const approvedLinks=await getMarketingDestinationLinks();const linkDirectory=Object.entries(approvedLinks).map(([key,url])=>`${key}: ${url}`).join("; ");
 const result=await streamChatWithMetadata([{role:"user",content:instruction}],()=>undefined,{provider:"auto",system:[
  "You are Cossa Social Media Manager, Social Media Specialist, Content Strategist, Content Creator and Content Writer. Do the strategic and writing work; do not make the operator construct the post for you.",
  `Platform: ${input.platform}. Selected business: ${business}. Selected objective: ${objective}.`,
  `VERIFIED COSSA BUSINESS KNOWLEDGE:\n${socialBusinessKnowledge(business)}`,
  `CONTENT OBJECTIVE RULE: ${socialObjectiveGuidance(objective)}`,
  "If business is auto, infer the single relevant Cossa business from the user's brief and verified knowledge. If objective is auto, infer the single strongest objective. Do not mix sales, awareness, education and engagement indiscriminately.",
  "Truth rule: use only facts in VERIFIED COSSA BUSINESS KNOWLEDGE, the operator brief, and approved links. Never invent capabilities, prices, discounts, stock, statistics, guarantees, testimonials, customers, integrations, results, locations or promotions. If a requested factual claim is unsupported, omit it rather than imagine it.",
  "Position each business according to its actual business model. Do not write SaaS like construction, ecommerce like consulting, the parent group like a subsidiary, or awareness copy like a hard-sale advertisement.",
  `Only approved destination links: ${linkDirectory||"default destination unavailable"}. Choose the destination_key matching the identified business. Never invent or alter a URL; the application attaches it after generation.`,
  "Return ONLY valid JSON with exactly these string keys: title, hook, caption, content, hashtags, cta, best_time, visual_idea, destination_key, business_key, objective.",
  "Write natural South African business English. The hook must fit the selected objective and audience. Hashtags must be relevant, not spammy. CTA intensity must match the objective: awareness/education can use a softer next step; sales/lead generation should use a clear commercial action.",
  "Do not say link below or link in bio unless appropriate; prefer a direct CTA matching the approved destination. best_time is a recommendation, not live analytics, unless evidence is supplied. Do not claim publishing, reach, engagement, trends or external actions without evidence."
 ].join("\n\n")});
 const raw=result.content.trim().replace(/^```json\s*/i,"").replace(/```$/i,"").trim();let parsed:Record<string,unknown>;try{parsed=JSON.parse(raw) as Record<string,unknown>;}catch{throw new Error("The Social Media Assistant returned an invalid content pack. Please generate again.");}const text=(key:string)=>sanitiseMarketingText(parsed[key]??"");const destination=resolveMarketingDestination(approvedLinks,text("destination_key"));const pack:SocialContentPack={title:text("title"),hook:text("hook"),caption:text("caption"),content:text("content"),hashtags:text("hashtags"),cta:text("cta"),best_time:text("best_time"),visual_idea:text("visual_idea"),destination_key:destination.key,link:destination.url,business_key:text("business_key")||business,objective:text("objective")||objective};if(!pack.content&&!pack.caption)throw new Error("The Social Media Assistant returned no usable post content.");return{pack,metadata:result.metadata};
}
export async function createCreativeMediaHandoff(input:{content:string;platform:string;instruction:string;}):Promise<{requestId:string}>{const content=sanitiseMarketingText(input.content);if(!content)throw new Error("Generate or enter customer-ready copy before sending a creative brief.");const state=creativeHandoffResult();const{data,error}=await db.from("creative_asset_requests").insert({organisation_id:COSSA_ORGANISATION_ID,title:`Content calendar visual brief — ${input.platform}`.slice(0,180),request_text:input.instruction.trim().slice(0,6000),asset_type:"social_graphic",platform:input.platform.trim().toLowerCase(),channels:[input.platform.trim().toLowerCase()],requirements:{source:"content_calendar",external_publication_authorised:false,generated_asset_confirmed:false},creative_brief:{copy:content,instruction:input.instruction.trim(),action:"brief_only"},copy_draft:content,lifecycle_status:state.lifecycleStatus,blocker_code:"creative_generation_not_started",blocker_message:"Creative brief recorded. No visual has been generated or published.",metadata:{source:"content_calendar_command"}}).select("id").single();if(error)throw new Error(`Creative brief could not be recorded: ${error.message}`);if(!data?.id)throw new Error("Creative brief did not return a saved request ID.");return{requestId:String(data.id)};}
export const contentAssistantDraftStatus=contentAssistantCalendarStatus;
