import {
  LayoutDashboard, Activity, Sparkles, Bell, Zap, Map,
  Megaphone, Search, MousePointerClick, Facebook, Share2, PenTool, Mail, MessageCircle, LayoutTemplate, Rocket, Palette,
  Users, UserPlus, GitBranch, UserCheck, Building2, CalendarDays, FileText, LineChart, BarChart3, Radar,
  Brain, Crown, Briefcase, Handshake, Headphones, Workflow, GitFork, BookMarked, Library, Mic, Database,
  FolderKanban, ListChecks, Calendar, Files, FileStack, FileBarChart, PieChart, Cog,
  Store, Settings as SettingsIcon,
  type LucideIcon,
} from "lucide-react";

export type ModuleStatus = "Planning" | "Design" | "Development" | "Testing" | "Live";

export interface ModuleItem {
  title: string;
  to: string;
  icon: LucideIcon;
  status: ModuleStatus;
  tagline: string;
  description: string;
  value: string;
  benefits: string[];
  roadmap: string[];
}

export interface ModuleGroup {
  label: string;
  items: ModuleItem[];
}

const s = (
  title: string, to: string, icon: LucideIcon, status: ModuleStatus,
  tagline: string, description: string, value: string, benefits: string[], roadmap: string[],
): ModuleItem => ({ title, to, icon, status, tagline, description, value, benefits, roadmap });

export const MODULES: ModuleGroup[] = [
  {
    label: "Command Center",
    items: [
      s("Dashboard", "/", LayoutDashboard, "Live",
        "Your AI Business Command Center",
        "A single pane of glass across marketing, sales, operations and AI insights — powered by the Cossa AI engine.",
        "See the entire business at a glance and act on what matters most, first.",
        ["Real-time KPIs", "AI daily briefing", "One-click actions", "Unified activity feed"],
        ["Live data connectors", "Personalised widgets", "Multi-business switching"]),
      s("Business Health", "/business-health", Activity, "Design",
        "360° Business Health Score",
        "AI grades every core function of your business — marketing, sales, service, ops, finance, online presence and automation.",
        "Know exactly where you're winning and where to fix the leaks.",
        ["Composite health score", "Category breakdown", "Trend history", "Improvement plan"],
        ["Benchmarks by industry", "AI-generated action plans", "Automated weekly review"]),
      s("AI Recommendations", "/ai-recommendations", Sparkles, "Design",
        "The next best action, always",
        "Cossa AI continuously scans your business and surfaces the highest-leverage next actions.",
        "Never guess what to do next — the AI tells you.",
        ["Prioritised actions", "One-click execution", "Explainable reasoning", "Impact estimates"],
        ["Autonomous execution", "Role-based suggestions", "Learning from outcomes"]),
      s("Notifications", "/notifications", Bell, "Development",
        "Everything important, nothing noisy",
        "AI-curated notifications from every module, ranked by business impact.",
        "Focus on what moves the needle.",
        ["Unified inbox", "Smart grouping", "Priority ranking", "Quiet hours"],
        ["Cross-channel delivery", "Escalation rules", "Team routing"]),
      s("Quick Actions", "/quick-actions", Zap, "Development",
        "Do more in fewer clicks",
        "Shortcut launcher for the most common actions across the platform.",
        "Save hours every week on repetitive workflows.",
        ["Create quote", "Add lead", "Log call", "Start campaign"],
        ["Custom shortcuts", "Voice-triggered actions", "Automation chaining"]),
      s("Cossa AI Roadmap", "/roadmap", Map, "Live",
        "Where Cossa AI is going",
        "Live view of the platform's development phases and delivery timeline.",
        "Full transparency into what's shipping and when.",
        ["Nine delivery phases", "Progress indicators", "Milestone breakdown"],
        ["Public changelog", "Feature voting", "Beta programme"]),
    ],
  },
  {
    label: "Marketing",
    items: [
      s("AI Marketing Director", "/marketing/ai-director", Megaphone, "Planning",
        "Your always-on marketing chief",
        "An AI marketing director that plans, launches and optimises campaigns across every channel.",
        "Enterprise-grade marketing strategy without the enterprise cost.",
        ["Strategic planning", "Channel mix", "Budget optimisation", "Performance review"],
        ["Autonomous campaign runs", "Creative generation", "Attribution modelling"]),
      s("SEO Center", "/marketing/seo", Search, "Planning",
        "Rank higher on Google, automatically",
        "Keyword research, on-page audits, content briefs and technical SEO — driven by AI.",
        "Compound organic traffic month after month.",
        ["Keyword tracking", "Site audits", "Content briefs", "Backlink monitor"],
        ["AI article generation", "Auto internal linking", "SERP watch"]),
      s("Google Ads", "/marketing/google-ads", MousePointerClick, "Planning",
        "Smarter Google Ads, less waste",
        "AI plans, launches and optimises Google Ads campaigns tuned to your goals.",
        "Lower cost per lead and higher ROAS.",
        ["Campaign builder", "Keyword mining", "Bid optimisation", "Creative testing"],
        ["Autonomous optimisation", "Cross-account reporting", "Offline conversion sync"]),
      s("Meta Ads", "/marketing/meta-ads", Facebook, "Planning",
        "Facebook & Instagram, on autopilot",
        "AI-managed Meta campaigns with creative generation and audience discovery.",
        "Scale paid social without a media buyer.",
        ["Campaign launcher", "Audience builder", "Creative variants", "Performance"],
        ["Auto-scaling budgets", "Lookalike engineering", "Reels-first creatives"]),
      s("Social Media", "/marketing/social", Share2, "Planning",
        "One inbox, all channels",
        "Plan, publish and respond across every social channel from one calendar.",
        "Stay consistently visible without living in the apps.",
        ["Content calendar", "Multi-channel publish", "Inbox", "Analytics"],
        ["AI captions", "Trend radar", "Reply suggestions"]),
      s("Content Studio", "/marketing/content-studio", PenTool, "Planning",
        "Generate premium content in minutes",
        "AI-powered studio for blog posts, ads, social, video scripts and email — on brand.",
        "Ship weeks of content in an afternoon.",
        ["Brand voice", "Templates", "Image generation", "Approval workflows"],
        ["Video generation", "Multi-language", "Repurposing engine"]),
      s("Email Marketing", "/marketing/email", Mail, "Planning",
        "Emails that convert",
        "Segments, sequences and broadcasts with AI copy and send-time optimisation.",
        "Turn your list into predictable revenue.",
        ["Segments", "Sequences", "Templates", "Analytics"],
        ["AI subject lines", "Predictive send time", "Deliverability guardrails"]),
      s("WhatsApp Marketing", "/marketing/whatsapp", MessageCircle, "Planning",
        "Reach customers where they reply",
        "WhatsApp Business campaigns, broadcasts and AI-assisted replies.",
        "Higher open rates than any other channel.",
        ["Broadcasts", "Templates", "Chatbot", "Opt-in management"],
        ["Catalog commerce", "AI agent handoff", "Payments"]),
      s("Landing Pages", "/marketing/landing-pages", LayoutTemplate, "Planning",
        "High-converting pages in minutes",
        "AI landing page builder tuned for South African audiences and payment gateways.",
        "Turn traffic into leads without a designer.",
        ["Templates", "AI copy", "Form builder", "A/B testing"],
        ["POPIA-ready forms", "PayFast/Ozow/Yoco", "Heatmaps"]),
      s("Campaigns", "/marketing/campaigns", Rocket, "Planning",
        "Cross-channel campaign command",
        "Unified planning and reporting for every campaign, every channel.",
        "One view of what's working and why.",
        ["Campaign brief", "Channel mix", "Timeline", "Rollup reporting"],
        ["Attribution", "Budget rebalancing", "AI post-mortems"]),
      s("Brand Management", "/marketing/brand", Palette, "Planning",
        "Your brand, protected and consistent",
        "Central brand hub for logos, colours, tone of voice and approved assets.",
        "Everything on-brand, everywhere.",
        ["Asset library", "Brand guidelines", "Tone of voice", "Approval flows"],
        ["Auto brand-check", "Asset generation", "Partner portals"]),
    ],
  },
  {
    label: "Sales",
    items: [
      s("CRM", "/sales/crm", Users, "Planning",
        "The CRM that thinks for you",
        "A modern CRM built around AI insight — not data entry.",
        "Spend time selling, not logging.",
        ["Contacts", "Deals", "Activities", "Timelines"],
        ["Auto-enrichment", "AI next steps", "Voice logging"]),
      s("Leads", "/sales/leads", UserPlus, "Planning",
        "Never miss a hot lead",
        "Capture, score and route leads from every channel with AI prioritisation.",
        "Convert more of the pipeline you already have.",
        ["Multi-source intake", "Lead scoring", "Assignment rules", "SLAs"],
        ["Predictive scoring", "Auto follow-up", "Enrichment"]),
      s("Pipeline", "/sales/pipeline", GitBranch, "Planning",
        "See every deal, clearly",
        "Kanban and forecast views with AI deal coaching.",
        "Predictable revenue.",
        ["Kanban", "Stages", "Forecast", "Deal rooms"],
        ["AI win probability", "Risk alerts", "Coaching prompts"]),
      s("Customers", "/sales/customers", UserCheck, "Planning",
        "Know your customers, deeply",
        "Unified customer profiles across every interaction.",
        "Retain more customers and grow LTV.",
        ["360° profile", "Interaction history", "Health score", "Segments"],
        ["Churn prediction", "Upsell suggestions", "NPS automation"]),
      s("Companies", "/sales/companies", Building2, "Planning",
        "Account-based intelligence",
        "Company profiles with related contacts, deals and activity.",
        "Sell into organisations, not just people.",
        ["Company profiles", "Hierarchies", "Related deals", "Activity"],
        ["Firmographic enrichment", "Intent signals", "Org charts"]),
      s("Appointments", "/sales/appointments", CalendarDays, "Planning",
        "Booking without the back and forth",
        "Smart scheduling with AI reminders and no-show reduction.",
        "More meetings, fewer no-shows.",
        ["Availability", "Booking pages", "Reminders", "Round-robin"],
        ["AI rescheduling", "Video links", "Payments upfront"]),
      s("Quotations", "/sales/quotations", FileText, "Planning",
        "Send stunning quotes fast",
        "AI-generated quotations with e-sign and payment links.",
        "Get paid faster.",
        ["Templates", "Product catalog", "E-sign", "Approvals"],
        ["AI pricing", "Auto follow-up", "Conversion analytics"]),
      s("Sales Forecast", "/sales/forecast", LineChart, "Planning",
        "Know next quarter today",
        "AI forecast rolled up from every deal in your pipeline.",
        "Plan hiring, stock and cash with confidence.",
        ["Weighted forecast", "Scenarios", "Rep rollups", "Trends"],
        ["ML forecasting", "Board-ready reports", "Alerts"]),
      s("Sales Analytics", "/sales/analytics", BarChart3, "Planning",
        "The metrics that actually matter",
        "Pre-built sales dashboards and AI diagnostics.",
        "Coach smarter, close faster.",
        ["Activity", "Conversion", "Velocity", "Leaderboards"],
        ["AI diagnostics", "Cohort analysis", "Custom dashboards"]),
      s("Lead Finder", "/sales/lead-finder", Radar, "Planning",
        "Find ideal customers on demand",
        "AI prospecting for South African SMEs with verified contact data.",
        "A predictable outbound engine.",
        ["ICP builder", "Company search", "Contact reveal", "List export"],
        ["Buying signals", "Auto-sequences", "CRM sync"]),
    ],
  },
  {
    label: "AI",
    items: [
      s("Cossa AI", "/ai/cossa", Brain, "Development",
        "Chat with your business",
        "The main AI assistant with full context on your business.",
        "An AI co-pilot for every decision.",
        ["Contextual chat", "Tool use", "Memory", "Attachments"],
        ["Voice mode", "Multi-agent teams", "Autonomous workflows"]),
      s("AI CEO", "/ai/ceo", Crown, "Planning",
        "Strategy on tap",
        "Executive-grade strategy sessions grounded in your real data.",
        "Board-level thinking on demand.",
        ["OKRs", "Strategic reviews", "Scenario planning"],
        ["Board packs", "Investor updates", "Autonomous planning"]),
      s("AI Business Consultant", "/ai/consultant", Briefcase, "Planning",
        "A consultant that knows your business",
        "Deep-dive advisory across marketing, sales, ops and finance.",
        "Consulting-firm insight, SME price.",
        ["Diagnostics", "Playbooks", "Action plans"],
        ["Industry benchmarks", "Peer comparisons", "Interventions"]),
      s("AI Sales Assistant", "/ai/sales-assistant", Handshake, "Planning",
        "A closer in your pocket",
        "Live call coaching, follow-ups, objection handling and email drafts.",
        "Every rep sells like your best rep.",
        ["Email drafts", "Call notes", "Follow-ups", "Objection library"],
        ["Live coaching", "Deal simulation", "Voice cloning"]),
      s("AI Customer Support", "/ai/support", Headphones, "Planning",
        "24/7 first-line support",
        "Autonomous support agent trained on your knowledge base.",
        "Instant answers, happier customers.",
        ["Chat widget", "Ticket triage", "Macros", "Handoff"],
        ["Voice support", "Proactive outreach", "CSAT prediction"]),
      s("AI Automation", "/ai/automation", Workflow, "Planning",
        "Automate anything",
        "Natural-language automations across every module and third-party app.",
        "Give the boring work to the AI.",
        ["Triggers", "Actions", "AI steps", "Approvals"],
        ["Multi-agent flows", "External APIs", "Marketplace recipes"]),
      s("Workflow Builder", "/ai/workflow", GitFork, "Planning",
        "Visual automation canvas",
        "Drag-and-drop workflow builder with AI steps.",
        "Ship complex automations without code.",
        ["Canvas", "Conditions", "Loops", "AI nodes"],
        ["Debugger", "Version history", "Templates"]),
      s("Prompt Library", "/ai/prompts", BookMarked, "Planning",
        "Reusable prompts, shared with your team",
        "A curated, versioned library of prompts and workflows.",
        "Institutional knowledge for your AI usage.",
        ["Categories", "Variables", "Sharing", "Ratings"],
        ["Prompt testing", "Autogen prompts", "Marketplace"]),
      s("Knowledge Base", "/ai/knowledge", Library, "Planning",
        "Your business, in one brain",
        "Upload documents, sites and data — the AI learns your business.",
        "Answers grounded in your truth.",
        ["Docs", "URLs", "Data sources", "Citations"],
        ["Auto-refresh", "Access control", "Semantic search"]),
      s("Voice AI", "/ai/voice", Mic, "Planning",
        "Talk to Cossa, hands-free",
        "Voice mode for capturing notes, running commands and handling calls.",
        "The fastest interface for busy operators.",
        ["Push-to-talk", "Voice notes", "Transcription"],
        ["Inbound calls", "Voice agents", "Real-time translation"]),
      s("AI Memory", "/ai/memory", Database, "Planning",
        "The AI remembers what matters",
        "Central memory store used by every AI agent in Cossa.",
        "Consistent, personalised AI everywhere.",
        ["Facts", "Preferences", "History"],
        ["Team memory", "Redaction", "Retention policies"]),
    ],
  },
  {
    label: "Operations",
    items: [
      s("Projects", "/operations/projects", FolderKanban, "Planning",
        "Deliver work on time",
        "Project workspaces with tasks, files and AI status updates.",
        "Fewer meetings, more delivered work.",
        ["Boards", "Timelines", "Files", "Discussions"],
        ["AI status", "Dependencies", "Portfolio view"]),
      s("Tasks", "/operations/tasks", ListChecks, "Planning",
        "The team to-do list",
        "Personal and team tasks with AI prioritisation.",
        "Nothing falls through the cracks.",
        ["My tasks", "Team tasks", "Priorities", "Due dates"],
        ["AI planning", "Recurring", "Focus mode"]),
      s("Calendar", "/operations/calendar", Calendar, "Planning",
        "One calendar for everything",
        "Unified calendar across meetings, tasks and campaigns.",
        "Own your week.",
        ["Day/week/month", "Sync", "Bookings"],
        ["AI scheduling", "Focus blocks", "Travel time"]),
      s("Documents", "/operations/documents", Files, "Planning",
        "Docs that write themselves",
        "AI-drafted documents with templates and collaboration.",
        "Faster drafts, better decisions.",
        ["Templates", "Collab", "Versioning"],
        ["AI drafting", "E-sign", "Doc-Q&A"]),
      s("NexDocs", "/operations/nexdocs", FileStack, "Planning",
        "Proposals, quotes and contracts",
        "The Cossa document engine for winning business.",
        "Send professional docs in minutes.",
        ["Proposals", "Contracts", "Quotes", "E-sign"],
        ["AI generation", "Payments", "Analytics"]),
      s("Reports", "/operations/reports", FileBarChart, "Planning",
        "Beautiful reports, automatically",
        "Scheduled reports across every module.",
        "Weekly leadership reviews in one click.",
        ["Templates", "Schedules", "Export"],
        ["AI narratives", "Custom builders", "White-label"]),
      s("Analytics", "/operations/analytics", PieChart, "Planning",
        "Unified analytics",
        "Cross-module analytics with AI diagnostics.",
        "Ask questions, get answers.",
        ["Dashboards", "Filters", "Exports"],
        ["Natural-language BI", "Anomaly detection", "Forecasting"]),
      s("Automation", "/operations/automation", Cog, "Planning",
        "Rule-based automations",
        "Simple if-this-then-that automations for operations.",
        "Save hours every week.",
        ["Triggers", "Actions", "Logs"],
        ["AI steps", "Webhooks", "Marketplace"]),
    ],
  },
  {
    label: "Platform",
    items: [
      s("Marketplace", "/marketplace", Store, "Planning",
        "Apps, templates and industry packs",
        "The Cossa marketplace for extensions and vertical solutions.",
        "Extend the platform without limits.",
        ["Apps", "Templates", "Industry packs", "Automations"],
        ["Developer program", "Revenue share", "Curated collections"]),
      s("Settings", "/settings", SettingsIcon, "Planning",
        "Workspace settings",
        "Manage your workspace, team and integrations.",
        "One place for control.",
        ["Workspace", "Team", "Integrations", "Billing"],
        ["Roles & permissions", "Audit log", "SSO"]),
    ],
  },
];

export const ALL_MODULES: ModuleItem[] = MODULES.flatMap((g) => g.items);
export const getModule = (to: string) => ALL_MODULES.find((m) => m.to === to);
