// This file is automatically generated. Keep custom transport safeguards small and explicit.
import { createClient } from "@supabase/supabase-js";
import { retrySupabaseIssuedAtFuture } from "@/lib/supabase-jwt-retry";
import type { Database } from "./types";

const GROWTH_LEAD_INTAKE_URL =
  "https://nptyyzyokzgnwnyteeyi.supabase.co/functions/v1/growth-lead-intake";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function inputUrl(input: RequestInfo | URL): string {
  if (typeof input === "string") return input;
  if (input instanceof URL) return input.toString();
  return input.url;
}

function extractGrowthLeadPayload(body: BodyInit | null | undefined) {
  if (typeof body !== "string") return null;

  try {
    const parsed = JSON.parse(body) as Record<string, unknown> | Array<Record<string, unknown>>;
    const row = Array.isArray(parsed) ? parsed[0] : parsed;

    if (!row || row.source !== "growth_website_quote_request") {
      return null;
    }

    const notes = typeof row.notes === "string" ? row.notes : "";
    const marker = "Customer request:\n";
    const markerIndex = notes.indexOf(marker);
    const message =
      markerIndex >= 0 ? notes.slice(markerIndex + marker.length).trim() : notes.trim();

    return {
      name:
        typeof row.name === "string"
          ? row.name
          : typeof row.full_name === "string"
            ? row.full_name
            : "",
      phone: typeof row.phone === "string" ? row.phone : "",
      email: typeof row.email === "string" ? row.email : "",
      message,
      page_url: typeof window !== "undefined" ? window.location.href : undefined,
    };
  } catch {
    return null;
  }
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    const url = inputUrl(input);
    const method = (
      init?.method ?? (input instanceof Request ? input.method : "GET")
    ).toUpperCase();
    const publicGrowthLead =
      method === "POST" && /\/rest\/v1\/leads(?:\?|$)/.test(url) && !headers.has("Authorization")
        ? extractGrowthLeadPayload(init?.body)
        : null;

    // The public GROWTH homepage used to post directly into public.leads. That table is
    // intentionally not writable by anonymous users. Route only the known public website
    // lead shape through the dedicated Edge Function; authenticated CRM traffic continues
    // to Supabase unchanged.
    if (publicGrowthLead) {
      return fetch(GROWTH_LEAD_INTAKE_URL, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(publicGrowthLead),
      });
    }

    headers.set("apikey", supabaseKey);
    const canReplay = ["GET", "HEAD", "OPTIONS"].includes(method);
    return retrySupabaseIssuedAtFuture(
      () => fetch(input, { ...init, headers }),
      canReplay,
    );
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Configure them in the Vercel project environment.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
